/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.Analysis;
import core.Exam;
import core.MedicalHistory;
import core.User;
import core.Patient;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Class for panel to create exams
 * @author AR
 */
public class CreateExam extends javax.swing.JPanel {

    Patient user;
    ArrayList<Analysis> analyses;
    MedicalHistory history;
    String fileName;

    /**
     * Creates new form CriarExame
     *
     * @param user
     * @param history
     * @param fileName
     */
    public CreateExam(Patient user, MedicalHistory history, String fileName) {
        initComponents();
        this.user = user;
        txtNameUser.setText(user.getName());
        txtNumUser.setText(user.getNumUtente());
        this.history = history;
        this.analyses = new ArrayList<>();
        this.fileName = fileName;
    }
    
    /**
     * Updates the user
     * 
     * @param user 
     */
    public void UpdateUser(Patient user) {
        this.user = user;
        txtNameUser.setText(user.getName());
        txtNumUser.setText(user.getNumUtente());
        this.analyses = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollShowEx = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSaveExam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNameAn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipoAn = new javax.swing.JTextField();
        btnAddAnalysis = new javax.swing.JButton();
        txtResAn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumUser = new javax.swing.JTextField();
        txtNameUser = new javax.swing.JTextField();
        lblAviso = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        prof = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(780, 400));
        setPreferredSize(new java.awt.Dimension(780, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scrollShowEx.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scrollShowEx.setViewportView(jTextArea1);

        btnSaveExam.setText("Finalizar Exame");
        btnSaveExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveExamActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado Atual Exame");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollShowEx, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnSaveExam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollShowEx, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveExam)
                .addContainerGap())
        );

        jLabel2.setText("Analise Resultado:");

        jLabel1.setText("Analise Nome:");

        jLabel3.setText("Tipo Analise:");

        btnAddAnalysis.setText("Adicionar Analise");
        btnAddAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTipoAn, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(txtNameAn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtResAn))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnAddAnalysis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNameAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtResAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btnAddAnalysis)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel5.setText("Utente Nº:");

        jLabel6.setText("Nome:");

        txtNumUser.setEditable(false);
        txtNumUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumUserActionPerformed(evt);
            }
        });

        txtNameUser.setEditable(false);

        lblAviso.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(255, 0, 0));
        lblAviso.setText("LABEL DE AVISO");
        lblAviso.setVisible(false);

        jLabel8.setText("Profissional:");

        prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblAviso))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumUser, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prof)
                                    .addComponent(txtNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNumUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumUserActionPerformed

    /**
     * Actions to preform when the button to add analysis is pressed
     * 
     * @param evt 
     */
    private void btnAddAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnalysisActionPerformed
        //variáveis para a execução deste evento
        String tipo = txtTipoAn.getText();
        String nome = txtNameAn.getText();
        String resultado = txtResAn.getText();
        Analysis analise = new Analysis(tipo, nome, resultado);

        //confirmar se o utilizador existe
        //-se existe, guardar conteudos dos ficheiros nas variáveis e 
        //proceder para a análise a inserir
        //-se não, escrever 'Patient não existe!!' em label de aviso e
        //torná-la visível
        //verificação de campos vazios  
        if (txtNumUser.getText().isBlank()
                || txtNameUser.getText().isBlank()
                || txtNameAn.getText().isBlank()
                || txtResAn.getText().isBlank()
                || txtTipoAn.getText().isBlank()
                || prof.getText().isBlank()) {

            lblAviso.setText("Todos os campos são obrigatórios!".toUpperCase());
            lblAviso.setVisible(true);

        } else {
            if ((lblAviso.getText().isBlank() || lblAviso.getText().matches("LABEL DE AVISO"))
                    && txtNameUser.getText().matches(user.getName())) {
                //Inserir análise em texto no seguinte formato:
                //------ANÁLISE DE <TIPO_ANALISE> (<NOME_ANALISE>)------
                //<RESULTADO>
                //-------------------------------------------------------
                jTextArea1.setText(jTextArea1.getText() + "------ANÁLISE DE " + tipo.toUpperCase()
                        + "(" + nome.toUpperCase() + ")------\n"
                        + "RESULTADO: " + resultado + "\n"
                        + "---------------------------------------------------\n");

                //Adicionar análise a arrayList
                analyses.add(analise);

                //limpar campos de parametros de exame
                txtNameAn.setText("");
                txtTipoAn.setText("");
                txtResAn.setText("");
            } else {
                lblAviso.setText("Utente não existe!!".toUpperCase());
                lblAviso.setVisible(true);
                txtNumUser.setText("");
                txtNameUser.setText("");
            }
        }
    }//GEN-LAST:event_btnAddAnalysisActionPerformed

    /**
     * Actions to preform when the button to add save an exam is pressed
     * 
     * @param evt 
     */
    private void btnSaveExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveExamActionPerformed

        //criar novo teste
        Exam test = new Exam(LocalDateTime.now(), user, prof.getText(), analyses);

        //guardar novo teste
        try {
            if (!prof.getText().isBlank()) {
                history.add(test);
                history.save(fileName);
            } else {
                JOptionPane.showMessageDialog(null, "Add Profesional");
            }
        } catch (IOException ex) {
            Logger.getLogger(CreateExam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CreateExam.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtNameAn.setText("");
        txtTipoAn.setText("");
        txtResAn.setText("");
        prof.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_btnSaveExamActionPerformed

    private void profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnalysis;
    private javax.swing.JButton btnSaveExam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JTextField prof;
    private javax.swing.JScrollPane scrollShowEx;
    private javax.swing.JTextField txtNameAn;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtNumUser;
    private javax.swing.JTextField txtResAn;
    private javax.swing.JTextField txtTipoAn;
    // End of variables declaration//GEN-END:variables
}
